### ISSUE TITLE
Spring Bot Beta Comms

### ISSUE THREAD

**Issue by robmoffat** [finos/spring-bot#309]
I think having a quick <2m video to introduce the concept and create a quick bot would be really helpful.  

Ideally, we can put this on LinkedIn along with our request for participants.

**Comment by robmoffat** [comment]
@abhishek-sinha-db and I have figured out the text of the announcement.  DB and FINOS are on-board to share the message.

**Comment by abhishek-sinha-db** [comment]
@robmoffat Can you share the final text which will go on blog . ?

**Comment by robmoffat** [comment]
Think I sent you before, but this is what I have:


> FINOS and Deutsche Bank would like to announce a new Spring Bot release!  
> 
> This is version 9 of this platform, used widely at DB for building complex chat-based workflows in Java.    However, for the first time, Spring Bot allows bots to communicate with users on both Symphony and Microsoft Teams platforms. Spring Bot follows Spring Web annotation conventions for creating bots.  Here is a short video to show how it works:
> 
> <2m video here, Abhi preparing this>
> 
> We are interested in finding other interested parties to work on integrations, so if you are in the business of building bots for either (or both) of these platforms, please get in touch.
> 
> https://springbot.finos.org/
> 
> https://github.com/finos/spring-bot

**Comment by abhishek-sinha-db** [comment]
Thanks Rob.. Just thought anything has changed ..
