### ISSUE TITLE
Move CustomHelpController to it's own demo bot

### ISSUE THREAD

**Issue by robmoffat** [finos/spring-bot#313]
## Bug Report

I've commented this out in demo-bot, since it doesn't work with teams.  Can we either fix it, or move to a new project and document it that it only works with Symphony?

I guess it'd be really nice if we had a template for teams too.

**Comment by pankaj-a-khandelwal-db** [comment]
It needed a Profile setting fix. Have added that now - This way Custom Help will be triggered when bot is deployed just to Symphony alone.
