### ISSUE TITLE
Upgrade to DatafeedV2 On Symphony

### ISSUE THREAD

**Issue by robmoffat** [finos/spring-bot#341]
V1 is now deprecated. We should use the new one.

**Comment by pankaj-a-khandelwal-db** [comment]
We will be testing out DatafeedV2 with a bot with more than 1 instances running. Once our analysis is validated, will upgrade demo bots to v2.

We are testing with DFv2 + Async (message processing option).
Sync message processing option leads to re-queuing of messages if not ACK'd in 30 secs.

NOTE: DFv2 + Async will spread messages across available instances of feed consuming bots. Though it might look like being load balanced; it is not. While spreading messages, it does not checks if previous messages delivered to same instance were processed or not.

**Comment by robmoffat** [comment]
We need to upgrade BDK and this will just happen to 2.7.0
