### ISSUE TITLE
Added the Pull request vulnerability check scan

### ISSUE THREAD

**Issue by abhishek-sinha-db** [finos/spring-bot#359]
### Description of Problem:
...what *problem* are you trying to solve that the project doesn't currently solve?

...please resist the temptation to describe your request in terms of a solution.  Job Story form ("When [triggering condition], I want to [motivation/goal], so I can [outcome].") can help ensure you're expressing a problem statement.

### Potential Solutions:
...clearly and concisely describe what you want to happen. Add any considered drawbacks.

... if you've considered alternatives, clearly and concisely describe those too.

**Comment by robmoffat** [comment]
add one of the actions from @maoo 's project https://github.com/maoo/security-scanning

**Comment by abhishek-sinha-db** [comment]
Is this FINOS standard one

**Comment by robmoffat** [comment]
yes

**Comment by robmoffat** [comment]
see #365
