### ISSUE TITLE
Error message through in 9.x if you send IM message

### ISSUE THREAD

**Issue by vaibhav-db** [finos/spring-bot#363]
### Steps to Reproduce:
 1. Send IM message to Bot like /help
2. You will received the help menu but in background error message through  

### Error Message:
 An unknown error occurred while trying to connect to https://db-test-2.symphony.com:443/pod. Please check below for more information: {"code":400,"message":"Either the stream you're trying to access does not exist, you're not allowed to view its details, or this stream is not a room."} 

 
## code
In PresentationMLHandler.onApplicationEvent it load the Room info, there BDK log the error and return null.
We should check the StreamType == ROOM then only load the RoomInfo

Same for ElementsHandler.accept, when user response in chat IM.

**Comment by pankaj-a-khandelwal-db** [comment]
For completeness - Though we see this error in logs, however there are no sideeffects of it. Code still works fine.
So, this can be considered more like a warning message (though could cause confusion, hence better to fix).
