### ISSUE TITLE
File Storage not working properly

### ISSUE THREAD

**Issue by abhishekdahiya-db** [finos/spring-bot#386]
File Storage not working properly.
if we send multiple work objects and try to retry one of the work object we always get the latest work object not the work object we are trying for.

**Comment by robmoffat** [comment]
Addressed by
- #385

**Comment by vaibhav-db** [comment]
Hi Rob, 

This bug is for file state storage. We have find when multiple room object inserted in file. It is not pulling the latest required object.
We have fixed this issue.

**Comment by robmoffat** [comment]
HI sorry I assigned the wrong Abhishek!  Did I link the wrong issue here?  Do we have a test that demonstrates this?

**Comment by vaibhav-db** [comment]
Yes we have same test `FileStateStorageTest`. No changes in test.

**Comment by robmoffat** [comment]
But the old test was working right?  If so, then there must be behaviour of the class that was not exercised by the test.  Can we extend the test so that it covers the missing behaviour?
